using System;
using System.Collections.Generic;
using TableDR;
#if !NodeExport
using NodeEditor.PortType;
using UnityEngine;
#else

#endif

namespace NodeEditor
{
    internal static partial class Constants
    {
        /// <summary>
        /// 技能编辑器配置，枚举定义配置列表
        /// </summary>
        public const string EnumConfigTitle = "【枚举定义配置】";

        /// <summary>
        /// 技能编辑器配置，程序操作列表
        /// </summary>
        public const string ProgrammerUseTitle = "【程序操作工具】";

        /// <summary>
        /// 节点编辑器配置
        /// </summary>
        public const string NodeEditorConfigTitle = "【节点编辑器配置】";

        #region 路径定义
        /// <summary>
        /// 编辑器路径
        /// </summary>
        public const string PathPrefix_NodeEditor = "Assets/Thirds/NodeEditor/";

        /// <summary>
        /// 编辑器说明路径
        /// </summary>
        public const string AnnotationDirPath = "Assets/Thirds/NodeEditor/0_说明文档/";

        /// <summary>
        /// 编辑器帮助文档路径
        /// </summary>
        public const string AnnotationHelpPath = "Assets/Thirds/NodeEditor/0_说明文档/0_说明文档.html";

        /// <summary>
        /// 派生Node代码模板路径
        /// </summary>
        public const string SubNodesScriptTemplatePath = PathPrefix_NodeEditor + "Template/SubConfigNodeTemplate.cs.txt";

        /// <summary>
        /// 派生VirtualNode代码模板路径
        /// </summary>
        public const string SubVirtualNodesScriptTemplatePath = PathPrefix_NodeEditor + "Template/SubVirtualNodeTemplate.cs.txt";

        /// <summary>
        /// Node代码模板路径
        /// </summary>
        public const string NodesScriptTemplatePath = PathPrefix_NodeEditor + "Template/ConfigNodeTemplate.cs.txt";

        /// <summary>
        /// 表格partial定义代码模板路径
        /// </summary>
        public const string TablePartialTemplatePath = PathPrefix_NodeEditor + "Template/TablePartialTemplate.cs.txt";

        /// <summary>
        /// Html说明模板路径
        /// </summary>
        public const string AnnotationHtmlTemplatePath = PathPrefix_NodeEditor + "Template/AnnotationTemplate.html.txt";

        /// <summary>
        /// 表格partial定义代码生成路径->TableDR_CS/NotHotfix
        /// </summary>
        public const string TablePartialPathNotHotfix = PathPrefix_NodeEditor + "TableDR_CS/NotHotfix/AutoGenerate/TablePartial.cs";

        /// <summary>
        /// 表格partial定义代码生成路径->TableDR_CS/Hotfix
        /// </summary>
        public const string TablePartialPathHotfix = PathPrefix_NodeEditor + "TableDR_CS/Hotfix/AutoGenerate/TablePartial.cs";

        /// <summary>
        /// 引用模板Node代码模板路径
        /// </summary>
        public const string RefTemplateNodesScriptTemplatePath = PathPrefix_NodeEditor + "Template/RefTemplateNodeTemplate.cs.txt";

        /// <summary>
        /// 表格结构的默认默认数据的代码模版
        /// </summary>
        public const string TableDefaultValueTemplatePath = PathPrefix_NodeEditor + "Template/TableDefaultVlue.cs.txt";

        /// <summary>
        /// 节点定义代码目录，如："Assets/Thirds/NodeEditor/SkillEditor/Nodes/SkillEffectConfig"
        /// </summary>
        public const string AutoGenerateDir = PathPrefix_NodeEditor + "AutoGenerate";

        /// <summary>
        /// 节点定义代码目录，如："Assets/Thirds/NodeEditor/SkillEditor/Nodes/SkillEffectConfig"
        /// </summary>
        public const string SubNodesScriptDir = AutoGenerateDir + "/Nodes";

        /// <summary>
        /// 节点定义代码目录，如："Assets/Thirds/NodeEditor/SkillEditor/Nodes/BaseConfig"
        /// </summary>
        public const string NodesScriptDir = SubNodesScriptDir + "/BaseConfig";

        /// <summary>
        /// 节点类型定义代码目录
        /// </summary>
        public const string TablePortTypeScriptPath = AutoGenerateDir + "/PortType/TablePortTypes.cs";
        #endregion

        #region Excel相关配置
        /// <summary>
        /// Excel路径
        /// </summary>
        public static readonly string ExcelPathPrefix = Application.dataPath + "/../../../Design/Excel/excel";
        /// <summary>
        /// 默认编辑器保存表格路径
        /// </summary>
        public static readonly string ConfigJsonPath = $"{ExcelPathPrefix}/{ConfigJsonName}";
        /// <summary>
        /// 默认表格配置路径
        /// </summary>
        public const string ConfigJsonName = "config.json";
        /// <summary>
        /// Manager后缀
        /// </summary>
        public const string TableManagerSuffix = "Manager";
        /// <summary>
        /// Table命名空间
        /// </summary>
        public const string TableNameSpace = "TableDR";

        /// <summary>
        /// 枚举静态接口前缀
        /// </summary>
        public const string EnumVDPefix = "@TableDR.EnumUtility.VD_";
        #endregion

        #region 节点配置说明

        /// <summary>
        /// 技能接口参数说明
        /// </summary>
        public const string EffectAnnotaionSheetName = "战斗-效果节点配置";

        /// <summary>
        /// 条件类型参数说明
        /// </summary>
        public const string ConditionAnnotaionSheetName = "战斗-条件节点配置";

        /// <summary>
        /// 筛选类型说明
        /// </summary>
        public const string SelectAnnotaionSheetName = "战斗-筛选节点配置";

        /// <summary>
        /// 基础类型参数说明
        /// </summary>
        public const string BaseConfigAnnotaionSheetName = "基础-表格节点配置";

        /// <summary>
        /// 属性定义参数说明
        /// </summary>
        public const string BattleNatureAnnotaionSheetName = "属性定义参数说明";

        /// <summary>
        /// 配置ID段说明列表
        /// </summary>
        public const string AnnotaionIDRange = "配置ID段说明列表";


        /// <summary>
        /// AI任务节点参数说明
        /// </summary>
        public const string AITaskNodeAnnotaionSheetName = "战斗-AI节点配置";

        /// <summary>
        /// AI任务节点参数说明
        /// </summary>
        public const string MapAnimAnnotaionSheetName = "大世界-地图动作";

        #endregion

#if !NodeExport
        #region 节点颜色
        public static readonly Color ColorEffect = new Color(0, 1, 0, 0.5f);
        public static readonly Color ColorSelect = new Color(1, 1, 0, 0.5f);
        public static readonly Color ColorCondition = new Color(1, 0, 1, 0.5f);
        public static readonly Color ColorSkill = new Color(1, 0, 0, 0.5f);
        public static readonly Color ColorSkillInterrupt = Color.gray;
        // TODO 细化节点颜色，支持多种类型颜色调和显示
        private static readonly Dictionary<string, Color> configColorMap = new Dictionary<string, Color>
        {
            {nameof(SkillEffectConfig),  ColorEffect},
            {nameof(SkillSelectConfig),  ColorSelect},
            {nameof(SkillConditionConfig),  ColorCondition},
            {nameof(SkillConfig),  ColorSkill},
            {nameof(SkillInterruptConfig),  ColorSkillInterrupt},

            {nameof(ISkillEffectConfig),  ColorEffect},
            {nameof(ISkillSelectConfig),  ColorSelect},
            {nameof(ISkillConditionConfig),  ColorCondition},
            {nameof(ISkillConfig),  ColorSkill},
            {nameof(ISkillInterruptConfig),  ColorSkillInterrupt},
        };
        #endregion

#endif
    }
}